spring:
  application:
    name: ChatBot

  datasource:
    url: jdbc:mysql://localhost:3307/chatbot
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          model: gemini-3.5-flash
          temperature: 0.7

        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001

    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: website_knowledge
        use-tls: false
        initialize-schema: true

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always